language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: thirionjl
  password:
    secure: OMWPpVYG0uFJ5TAwVm1kK+zagT73HXvaDwDDUuwwfFUqx6AqwBgmIxoCJIo2uAZQchm1zmL8JunJoNH+eTqKn5zm7cjsRWQZSF5UBwmUBasnrwPy9lRpijv6M9G2CC/CVqLppdygpBOgKoaPoc2UDXcTqyHyQ5QmyrR1ZGqNE02Usm71/15CFD4rQqGdVKoX+H9WeXx+cbBS0CyB5TFmB6d2mWNrVxxI83UEPg650igmJ7f6h0npgJy7oxq4jdftXalgV2WOn4u5KWjHXp66smLAQhF2+uNcWSPpbQ4XBtHkuDuKbC6trDyjVQ41MVdN9kXDQDGAQSnHuMryq+EebfNgnn+1RJ/Dw9myvyDBes6EgcIIpbUlBggCc1jx/WoEOvCYeQ4qNAyoQXzgInASIi7HIUzc9ZiOyY6Iy0s/w3a/hzWaNjCDrOHNSoZOJ9djX3iJGgAKWue91a9S/wyRtfpisZ/dr2OcQh2zS+zOsLPfJuXOmnjFYC9amyOrnHeTDyO3srjU0WtztTgFqO2Ww17M14S6HjuDgCHNNsP6o7j33hzt91i5i0jrK3eEBXdlSmINIDYN+jrO6WTG92IydQ7+r1QsMiW1H351YiqdwBLdDdCtJ6O+ulQuPrGi58UWqed4/ika9+0I7yjhZY5SzYCe4kCOq+5bxCJ0Ronjs44=
  on:
    tags: true
    repo: thirionjl/chains
    python: 3.6
