name: chains-dev
channels:
  - defaults
dependencies:
  - python=3.10
  - blas[build=*mkl]
  - h5py
  - pytest
  - tensorflow
  - matplotlib
  - scikit-learn
  - pip
  - graphviz
  - texttable
  - pip:
      - daz
